name: Build and Publish

env:
  GHR_COMPRESS: xz
  GHR_PATH: build/
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: GitHub Releases
      # You may pin to the exact commit or the version.
      # uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f
      uses: fnkr/github-action-ghr@v1.3
